"use strict";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d");
const scoreEl=document.getElementById("score"),statusEl=document.getElementById("status");
let W=innerWidth,H=innerHeight,dpr=1,paused=false,score=0,last=performance.now(),spawnT=0,id=0;
const nodes=[],edges=[],cars=[];
const COLORS=["#ff6b6b","#58a6ff","#ffd166","#7ee787","#c084fc","#fb923c"];
const houses=[],targets=[];
function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(dpr,0,0,dpr,0,0);layout()}addEventListener("resize",resize);
function layout(){if(nodes.length)return;const sx=W/900,sy=H/600;[[.15,.23],[.5,.16],[.85,.23],[.15,.77],[.5,.84],[.85,.77],[.3,.5],[.7,.5]].forEach((p,i)=>nodes.push({id:i,x:p[0]*W,y:p[1]*H}));[[0,1],[1,2],[3,4],[4,5],[0,3],[1,4],[2,5],[1,6],[1,7],[4,6],[4,7],[6,7]].forEach(([a,b])=>addEdge(a,b));for(let i=0;i<3;i++){houses.push({node:i,color:COLORS[i]});targets.push({node:5-i,color:COLORS[i]})}}
function addEdge(a,b){if(a===b||edges.some(e=>(e.a===a&&e.b===b)||(e.a===b&&e.b===a)))return;edges.push({a,b})}
function neighbors(n){const out=[];for(const e of edges){if(e.a===n)out.push(e.b);else if(e.b===n)out.push(e.a)}return out}
function pathfind(start,goal){const q=[start],prev=new Map([[start,null]]);while(q.length){const n=q.shift();if(n===goal)break;for(const x of neighbors(n))if(!prev.has(x)){prev.set(x,n);q.push(x)}}if(!prev.has(goal))return null;const p=[];for(let n=goal;n!==null;n=prev.get(n))p.push(n);return p.reverse()}
function spawn(){const h=houses[Math.floor(Math.random()*houses.length)], choices=targets.filter(t=>t.color===h.color);const t=choices[0];const p=pathfind(h.node,t.node);if(!p||p.length<2)return;const n=nodes[p[0]], next=nodes[p[1]];cars.push({id:++id,color:h.color,path:p,seg:0,t:0,speed:0,dead:0,x:n.x,y:n.y,angle:Math.atan2(next.y-n.y,next.x-n.x),done:false})}
function update(dt){spawnT+=dt;if(spawnT>.72&&cars.length<130){spawnT=0;spawn()}const step=Math.min(dt,.05);for(const c of cars){if(c.done)continue;const a=nodes[c.path[c.seg]],b=nodes[c.path[c.seg+1]];if(!a||!b){c.done=true;continue}let desired=120;let closest=null,best=999;for(const o of cars){if(o===c||o.done)continue;const dx=o.x-c.x,dy=o.y-c.y,d=Math.hypot(dx,dy),ahead=dx*Math.cos(c.angle)+dy*Math.sin(c.angle),side=Math.abs(-dx*Math.sin(c.angle)+dy*Math.cos(c.angle));if(ahead>0&&ahead<50&&side<12&&ahead<best){best=ahead;closest=o}}if(closest)desired=Math.min(desired,Math.max(0,(best-24)*5));const acc=desired>c.speed?240:-360;c.speed=Math.max(0,Math.min(desired,c.speed+acc*step));c.t+=c.speed*step/Math.max(1,Math.hypot(b.x-a.x,b.y-a.y));if(c.t>=1){c.t-=1;c.seg++;if(c.seg>=c.path.length-1){c.done=true;score+=100;continue}}const aa=nodes[c.path[c.seg]],bb=nodes[c.path[c.seg+1]];c.x=aa.x+(bb.x-aa.x)*c.t;c.y=aa.y+(bb.y-aa.y)*c.t;c.angle=Math.atan2(bb.y-aa.y,bb.x-aa.x);c.dead=c.speed<2?c.dead+step:0;if(c.dead>5){const np=pathfind(c.path[c.seg],c.path[c.path.length-1]);if(np){c.path=np;c.seg=0;c.t=0;c.dead=0}}}for(let i=cars.length-1;i>=0;i--)if(cars[i].done)cars.splice(i,1)}
function drawRoad(e){const a=nodes[e.a],b=nodes[e.b],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx);ctx.save();ctx.translate(a.x,a.y);ctx.rotate(ang);ctx.fillStyle="#313943";ctx.fillRect(0,-16,len,32);ctx.strokeStyle="#5d6670";ctx.lineWidth=1;ctx.strokeRect(0,-16,len,32);ctx.strokeStyle="#ffffff44";ctx.lineWidth=2;ctx.setLineDash([12,12]);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(len,0);ctx.stroke();ctx.restore()}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle="#182028";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#ffffff04";ctx.lineWidth=1;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}edges.forEach(drawRoad);houses.forEach(h=>drawBuilding(nodes[h.node],h.color,true));targets.forEach(t=>drawBuilding(nodes[t.node],t.color,false));for(const c of cars){ctx.save();ctx.translate(c.x,c.y);ctx.rotate(c.angle);ctx.fillStyle="#10151b";ctx.fillRect(-11,-6,22,12);ctx.fillStyle=c.color;ctx.fillRect(-8,-5,14,10);ctx.fillStyle="#dcefff";ctx.fillRect(1,-4,5,8);ctx.restore()}for(const n of nodes){ctx.fillStyle="#67717c";ctx.beginPath();ctx.arc(n.x,n.y,4,0,Math.PI*2);ctx.fill()}scoreEl.textContent=score.toLocaleString();statusEl.textContent=paused?"PAUSED":cars.length+" CARS"}
function drawBuilding(n,color,house){ctx.save();ctx.translate(n.x,n.y);ctx.fillStyle=color;ctx.globalAlpha=.9;ctx.beginPath();ctx.arc(0,0,house?15:19,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#10151b";ctx.font="bold 12px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(house?"⌂":"●",0,1);ctx.restore()}
function loop(now){const dt=(now-last)/1000;last=now;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
document.getElementById("pause").onclick=()=>paused=!paused;
document.getElementById("reset").onclick=()=>{cars.length=0;score=0;spawnT=0};
canvas.addEventListener("pointerdown",e=>{if(e.target!==canvas)return;});
resize();for(let i=0;i<8;i++)spawn();requestAnimationFrame(loop);
